### ISSUE TITLE
error when running node from folder

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/integration-tests#10]
i've configured a local folder instead of a github repo, got this:
```
/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/supercop.js/lib.js:97
      throw ex;
      ^

Error: Cannot find module '../bin/tendermint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/tendermint-node/src/index.js:10:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/johann/dev/leapdao-integ-tests/build/node/node_modules/tendermint-node/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/johann/dev/leapdao-integ-tests/build/node/lotion/lib/tendermint.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

**Comment by troggy** [comment]
not reproduced
